package com.sansfile.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AppNotificationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppNotificationAllPropertiesEquals(AppNotification expected, AppNotification actual) {
        assertAppNotificationAutoGeneratedPropertiesEquals(expected, actual);
        assertAppNotificationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppNotificationAllUpdatablePropertiesEquals(AppNotification expected, AppNotification actual) {
        assertAppNotificationUpdatableFieldsEquals(expected, actual);
        assertAppNotificationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppNotificationAutoGeneratedPropertiesEquals(AppNotification expected, AppNotification actual) {
        assertThat(actual)
            .as("Verify AppNotification auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppNotificationUpdatableFieldsEquals(AppNotification expected, AppNotification actual) {
        assertThat(actual)
            .as("Verify AppNotification relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getMessage()).as("check message").isEqualTo(expected.getMessage()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getRecipientRole()).as("check recipientRole").isEqualTo(expected.getRecipientRole()))
            .satisfies(a -> assertThat(a.getIsRead()).as("check isRead").isEqualTo(expected.getIsRead()))
            .satisfies(a -> assertThat(a.getTargetRoute()).as("check targetRoute").isEqualTo(expected.getTargetRoute()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppNotificationUpdatableRelationshipsEquals(AppNotification expected, AppNotification actual) {
        // empty method
    }
}
