package com.sansfile.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BoutiqueOrderAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBoutiqueOrderAllPropertiesEquals(BoutiqueOrder expected, BoutiqueOrder actual) {
        assertBoutiqueOrderAutoGeneratedPropertiesEquals(expected, actual);
        assertBoutiqueOrderAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBoutiqueOrderAllUpdatablePropertiesEquals(BoutiqueOrder expected, BoutiqueOrder actual) {
        assertBoutiqueOrderUpdatableFieldsEquals(expected, actual);
        assertBoutiqueOrderUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBoutiqueOrderAutoGeneratedPropertiesEquals(BoutiqueOrder expected, BoutiqueOrder actual) {
        assertThat(actual)
            .as("Verify BoutiqueOrder auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBoutiqueOrderUpdatableFieldsEquals(BoutiqueOrder expected, BoutiqueOrder actual) {
        assertThat(actual)
            .as("Verify BoutiqueOrder relevant properties")
            .satisfies(a -> assertThat(a.getOrderNumber()).as("check orderNumber").isEqualTo(expected.getOrderNumber()))
            .satisfies(a -> assertThat(a.getSubtotal()).as("check subtotal").isEqualTo(expected.getSubtotal()))
            .satisfies(a -> assertThat(a.getDeliveryFee()).as("check deliveryFee").isEqualTo(expected.getDeliveryFee()))
            .satisfies(a -> assertThat(a.getTotalPrice()).as("check totalPrice").isEqualTo(expected.getTotalPrice()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getOrderType()).as("check orderType").isEqualTo(expected.getOrderType()))
            .satisfies(a -> assertThat(a.getDeliveryAddress()).as("check deliveryAddress").isEqualTo(expected.getDeliveryAddress()))
            .satisfies(a -> assertThat(a.getDeliveryDistrict()).as("check deliveryDistrict").isEqualTo(expected.getDeliveryDistrict()))
            .satisfies(a -> assertThat(a.getCustomerName()).as("check customerName").isEqualTo(expected.getCustomerName()))
            .satisfies(a -> assertThat(a.getCustomerPhone()).as("check customerPhone").isEqualTo(expected.getCustomerPhone()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBoutiqueOrderUpdatableRelationshipsEquals(BoutiqueOrder expected, BoutiqueOrder actual) {
        // empty method
    }
}
