package com.sansfile.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CoiffeurProfileAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCoiffeurProfileAllPropertiesEquals(CoiffeurProfile expected, CoiffeurProfile actual) {
        assertCoiffeurProfileAutoGeneratedPropertiesEquals(expected, actual);
        assertCoiffeurProfileAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCoiffeurProfileAllUpdatablePropertiesEquals(CoiffeurProfile expected, CoiffeurProfile actual) {
        assertCoiffeurProfileUpdatableFieldsEquals(expected, actual);
        assertCoiffeurProfileUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCoiffeurProfileAutoGeneratedPropertiesEquals(CoiffeurProfile expected, CoiffeurProfile actual) {
        assertThat(actual)
            .as("Verify CoiffeurProfile auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCoiffeurProfileUpdatableFieldsEquals(CoiffeurProfile expected, CoiffeurProfile actual) {
        assertThat(actual)
            .as("Verify CoiffeurProfile relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getPhone()).as("check phone").isEqualTo(expected.getPhone()))
            .satisfies(a -> assertThat(a.getSpecialty()).as("check specialty").isEqualTo(expected.getSpecialty()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()))
            .satisfies(a -> assertThat(a.getAvatarUrl()).as("check avatarUrl").isEqualTo(expected.getAvatarUrl()))
            .satisfies(a ->
                assertThat(a.getTicketsServedCount()).as("check ticketsServedCount").isEqualTo(expected.getTicketsServedCount())
            )
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCoiffeurProfileUpdatableRelationshipsEquals(CoiffeurProfile expected, CoiffeurProfile actual) {
        assertThat(actual)
            .as("Verify CoiffeurProfile relationships")
            .satisfies(a -> assertThat(a.getSalon()).as("check salon").isEqualTo(expected.getSalon()));
    }
}
