package com.sansfile.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FavoriteSalonAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFavoriteSalonAllPropertiesEquals(FavoriteSalon expected, FavoriteSalon actual) {
        assertFavoriteSalonAutoGeneratedPropertiesEquals(expected, actual);
        assertFavoriteSalonAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFavoriteSalonAllUpdatablePropertiesEquals(FavoriteSalon expected, FavoriteSalon actual) {
        assertFavoriteSalonUpdatableFieldsEquals(expected, actual);
        assertFavoriteSalonUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFavoriteSalonAutoGeneratedPropertiesEquals(FavoriteSalon expected, FavoriteSalon actual) {
        assertThat(actual)
            .as("Verify FavoriteSalon auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFavoriteSalonUpdatableFieldsEquals(FavoriteSalon expected, FavoriteSalon actual) {
        assertThat(actual)
            .as("Verify FavoriteSalon relevant properties")
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFavoriteSalonUpdatableRelationshipsEquals(FavoriteSalon expected, FavoriteSalon actual) {
        assertThat(actual)
            .as("Verify FavoriteSalon relationships")
            .satisfies(a -> assertThat(a.getSalon()).as("check salon").isEqualTo(expected.getSalon()));
    }
}
