package com.sansfile.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OtpVerificationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOtpVerificationAllPropertiesEquals(OtpVerification expected, OtpVerification actual) {
        assertOtpVerificationAutoGeneratedPropertiesEquals(expected, actual);
        assertOtpVerificationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOtpVerificationAllUpdatablePropertiesEquals(OtpVerification expected, OtpVerification actual) {
        assertOtpVerificationUpdatableFieldsEquals(expected, actual);
        assertOtpVerificationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOtpVerificationAutoGeneratedPropertiesEquals(OtpVerification expected, OtpVerification actual) {
        assertThat(actual)
            .as("Verify OtpVerification auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOtpVerificationUpdatableFieldsEquals(OtpVerification expected, OtpVerification actual) {
        assertThat(actual)
            .as("Verify OtpVerification relevant properties")
            .satisfies(a -> assertThat(a.getPhone()).as("check phone").isEqualTo(expected.getPhone()))
            .satisfies(a -> assertThat(a.getCodeHash()).as("check codeHash").isEqualTo(expected.getCodeHash()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getAttemptsCount()).as("check attemptsCount").isEqualTo(expected.getAttemptsCount()))
            .satisfies(a -> assertThat(a.getExpiresAt()).as("check expiresAt").isEqualTo(expected.getExpiresAt()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOtpVerificationUpdatableRelationshipsEquals(OtpVerification expected, OtpVerification actual) {
        // empty method
    }
}
