package com.sansfile.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PlatformSettingsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlatformSettingsAllPropertiesEquals(PlatformSettings expected, PlatformSettings actual) {
        assertPlatformSettingsAutoGeneratedPropertiesEquals(expected, actual);
        assertPlatformSettingsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlatformSettingsAllUpdatablePropertiesEquals(PlatformSettings expected, PlatformSettings actual) {
        assertPlatformSettingsUpdatableFieldsEquals(expected, actual);
        assertPlatformSettingsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlatformSettingsAutoGeneratedPropertiesEquals(PlatformSettings expected, PlatformSettings actual) {
        assertThat(actual)
            .as("Verify PlatformSettings auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlatformSettingsUpdatableFieldsEquals(PlatformSettings expected, PlatformSettings actual) {
        assertThat(actual)
            .as("Verify PlatformSettings relevant properties")
            .satisfies(a -> assertThat(a.getAppName()).as("check appName").isEqualTo(expected.getAppName()))
            .satisfies(a -> assertThat(a.getContactEmail()).as("check contactEmail").isEqualTo(expected.getContactEmail()))
            .satisfies(a -> assertThat(a.getContactPhone()).as("check contactPhone").isEqualTo(expected.getContactPhone()))
            .satisfies(a -> assertThat(a.getCommissionRate()).as("check commissionRate").isEqualTo(expected.getCommissionRate()))
            .satisfies(a -> assertThat(a.getOpeningTime()).as("check openingTime").isEqualTo(expected.getOpeningTime()))
            .satisfies(a -> assertThat(a.getClosingTime()).as("check closingTime").isEqualTo(expected.getClosingTime()))
            .satisfies(a ->
                assertThat(a.getAllowRelativeBooking()).as("check allowRelativeBooking").isEqualTo(expected.getAllowRelativeBooking())
            )
            .satisfies(a -> assertThat(a.getMaintenanceMode()).as("check maintenanceMode").isEqualTo(expected.getMaintenanceMode()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlatformSettingsUpdatableRelationshipsEquals(PlatformSettings expected, PlatformSettings actual) {
        // empty method
    }
}
