package com.sansfile.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RelativeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRelativeAllPropertiesEquals(Relative expected, Relative actual) {
        assertRelativeAutoGeneratedPropertiesEquals(expected, actual);
        assertRelativeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRelativeAllUpdatablePropertiesEquals(Relative expected, Relative actual) {
        assertRelativeUpdatableFieldsEquals(expected, actual);
        assertRelativeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRelativeAutoGeneratedPropertiesEquals(Relative expected, Relative actual) {
        assertThat(actual)
            .as("Verify Relative auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRelativeUpdatableFieldsEquals(Relative expected, Relative actual) {
        assertThat(actual)
            .as("Verify Relative relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getRelation()).as("check relation").isEqualTo(expected.getRelation()))
            .satisfies(a -> assertThat(a.getPhone()).as("check phone").isEqualTo(expected.getPhone()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRelativeUpdatableRelationshipsEquals(Relative expected, Relative actual) {
        // empty method
    }
}
