package com.sansfile.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SalonAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalonAllPropertiesEquals(Salon expected, Salon actual) {
        assertSalonAutoGeneratedPropertiesEquals(expected, actual);
        assertSalonAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalonAllUpdatablePropertiesEquals(Salon expected, Salon actual) {
        assertSalonUpdatableFieldsEquals(expected, actual);
        assertSalonUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalonAutoGeneratedPropertiesEquals(Salon expected, Salon actual) {
        assertThat(actual)
            .as("Verify Salon auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalonUpdatableFieldsEquals(Salon expected, Salon actual) {
        assertThat(actual)
            .as("Verify Salon relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getSlug()).as("check slug").isEqualTo(expected.getSlug()))
            .satisfies(a -> assertThat(a.getLocation()).as("check location").isEqualTo(expected.getLocation()))
            .satisfies(a -> assertThat(a.getDistrict()).as("check district").isEqualTo(expected.getDistrict()))
            .satisfies(a -> assertThat(a.getAddress()).as("check address").isEqualTo(expected.getAddress()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getPhone()).as("check phone").isEqualTo(expected.getPhone()))
            .satisfies(a -> assertThat(a.getOpeningHours()).as("check openingHours").isEqualTo(expected.getOpeningHours()))
            .satisfies(a ->
                assertThat(a.getEstimatedWaitMinutes()).as("check estimatedWaitMinutes").isEqualTo(expected.getEstimatedWaitMinutes())
            )
            .satisfies(a -> assertThat(a.getPeopleWaiting()).as("check peopleWaiting").isEqualTo(expected.getPeopleWaiting()))
            .satisfies(a -> assertThat(a.getAvatarUrl()).as("check avatarUrl").isEqualTo(expected.getAvatarUrl()))
            .satisfies(a -> assertThat(a.getCoverUrl()).as("check coverUrl").isEqualTo(expected.getCoverUrl()))
            .satisfies(a -> assertThat(a.getLatitude()).as("check latitude").isEqualTo(expected.getLatitude()))
            .satisfies(a -> assertThat(a.getLongitude()).as("check longitude").isEqualTo(expected.getLongitude()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalonUpdatableRelationshipsEquals(Salon expected, Salon actual) {
        // empty method
    }
}
