package com.sansfile.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SalonActionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalonActionAllPropertiesEquals(SalonAction expected, SalonAction actual) {
        assertSalonActionAutoGeneratedPropertiesEquals(expected, actual);
        assertSalonActionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalonActionAllUpdatablePropertiesEquals(SalonAction expected, SalonAction actual) {
        assertSalonActionUpdatableFieldsEquals(expected, actual);
        assertSalonActionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalonActionAutoGeneratedPropertiesEquals(SalonAction expected, SalonAction actual) {
        assertThat(actual)
            .as("Verify SalonAction auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalonActionUpdatableFieldsEquals(SalonAction expected, SalonAction actual) {
        assertThat(actual)
            .as("Verify SalonAction relevant properties")
            .satisfies(a -> assertThat(a.getLabel()).as("check label").isEqualTo(expected.getLabel()))
            .satisfies(a -> assertThat(a.getIcon()).as("check icon").isEqualTo(expected.getIcon()))
            .satisfies(a -> assertThat(a.getHref()).as("check href").isEqualTo(expected.getHref()))
            .satisfies(a -> assertThat(a.getSortOrder()).as("check sortOrder").isEqualTo(expected.getSortOrder()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalonActionUpdatableRelationshipsEquals(SalonAction expected, SalonAction actual) {
        assertThat(actual)
            .as("Verify SalonAction relationships")
            .satisfies(a -> assertThat(a.getSalon()).as("check salon").isEqualTo(expected.getSalon()));
    }
}
