# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME:sansfile_user}
    password: ${SPRING_DATASOURCE_PASSWORD:sansfile_secure_password}

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: NDQ3NDc5Y2Y5M2U4OTFjODNlMTc5YjViMTFlZmRjZDJiNGRlMzkzZGY3YzE3ODM2ZjQ0MjYwZmMyMzc2MjYzZGViYzlhMTQ5YTc1NzI3NTMzNDk1NTg1ZTczMWIzMDc4N2IxMDAwYmY0YTEyOTAzYTZkZjdhZTE3YzFmMjIzN2E=
